# Generated by Django 5.2.1 on 2025-05-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
         migrations.CreateModel(
            name='TypeChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('options', models.TextField(default='')),
                ('typeChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.typechoice')),

            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
       
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.form')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.section')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phon1e', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.state')),
            ],
        ),
       
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(verbose_name='date visited')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.form')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.review')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.visitor')),
            ],
        ),
    ]
